@DddEf.Api_HostAddress = https://localhost:7229

POST {{DddEf.Api_HostAddress}}/api/items/Create
Content-Type: application/json

{
  "ItemCode":"Code001",
  "ItemName":"Name001"
}

###

POST {{DddEf.Api_HostAddress}}/api/customers/add
Content-Type: application/json

{
  "CustomerCode":"C002",
  "CustomerName":"N002"
}

###
POST {{DddEf.Api_HostAddress}}/api/customers/update
Content-Type: application/json

{
  "Id":"BDBBACC4-748E-46C1-B3C8-55E919728307",
  "CustomerCode":"C002",
  "CustomerName":"N002"
}